---
deployment:
 tasks:
 - export DEPLOYPATH=/home/shterate/absensi.shteratecabangblitar.org/
 - /bin/cp -R application $DEPLOYPATH
 - /bin/cp -R system $DEPLOYPATH
 - /bin/cp -R assets $DEPLOYPATH
 - /bin/cp index.php  $DEPLOYPATH
 - /bin/cp .htaccess  $DEPLOYPATH
 - /bin/cp .composer.json  $DEPLOYPATH
 - /bin/cp .composer.lock  $DEPLOYPATH